### ISSUE TITLE
monkeyYaml is confused

### ISSUE THREAD

**Issue by arv** [tc39/test262#345]
monkeyYaml fails on https://github.com/tc39/test262/blob/master/test/built-ins/Object/assign/ObjectOverride-sameproperty.js with the error mesage

```
Traceback (most recent call last):
  File "/mnt/data/b/build/slave/linux/build/v8/tools/run-tests.py", line 692, in <module>
    sys.exit(Main())
  File "/mnt/data/b/build/slave/linux/build/v8/tools/run-tests.py", line 518, in Main
    code = Execute(arch, mode, args, options, suites, workspace)
  File "/mnt/data/b/build/slave/linux/build/v8/tools/run-tests.py", line 618, in Execute
    for v in s.VariantFlags(t, variant_flags) ]
  File "/mnt/data/b/build/slave/linux/build/v8/test/test262-es6/testcfg.py", line 86, in VariantFlags
    test_record = self.GetTestRecord(testcase)
  File "/mnt/data/b/build/slave/linux/build/v8/test/test262-es6/testcfg.py", line 114, in GetTestRecord
    testcase.path)
  File "/mnt/data/b/build/slave/linux/build/v8/test/test262-es6/data/tools/packaging/parseTestRecord.py", line 106, in parseTestRecord
    yamlAttrParser(testRecord, attrs, name)
  File "/mnt/data/b/build/slave/linux/build/v8/test/test262-es6/data/tools/packaging/parseTestRecord.py", line 81, in yamlAttrParser
    parsed = yamlLoad(body)
  File "/mnt/data/b/build/slave/linux/build/v8/test/test262-es6/data/tools/packaging/monkeyYaml.py", line 33, in load
    raise Exception("monkeyYaml is confused at " + line)
Exception: monkeyYaml is confused at              i.e. a later assignment to the same property overrides an earlier assignment.
```

@smikes

**Comment by jugglinmike** [comment]
That looks like invalid YAML. I'll submit a patch to fix it post-haste

**Comment by jugglinmike** [comment]
Looks like I spoke too soon: [YAML supports line folding](http://www.yaml.org/spec/1.2/spec.html#id2779048), so monkeyYAML should probably be updated.

**Comment by arv** [comment]
I'm fixing monkeyYaml. Almost done.

**Comment by jugglinmike** [comment]
Great!
