### ISSUE TITLE
ESVU Chakra installation fails in CI

### ISSUE THREAD

**Issue by ptomato** [tc39/test262#3953]
As if we hadn't just fixed one of the other CI jobs ... Chakra has started failing since yesterday.
```
esvu ❯ version 1.2.12
Chakra ❯ Checking version...
Chakra ❯ Installing version 1_11_24
Chakra ❯ Downloading https://aka.ms/chakracore/cc_linux_x64_1_11_24
Chakra ❯ Extracting /tmp/esvu-d7054239fcf6e75c74c83cb80f5b3dd1.gz
Chakra ❯ Installing /tmp/esvu-d7054239fcf6e75c74c83cb80f5b3dd1.gz-extracted
Chakra ❯ Testing...
esvu ✖ Error: Command was killed with SIGABRT (Aborted): /home/circleci/.esvu/bin/chakra /tmp/esvu_chakra_test.js
The futex facility returned an unexpected error code.
    at makeError (/home/circleci/test262/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/circleci/test262/node_modules/execa/index.js:114:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChakraInstaller.test (/home/circleci/test262/node_modules/esvu/src/engines/chakra.js:77:8)
    at async ChakraInstaller.install (/home/circleci/test262/node_modules/esvu/src/installer.js:110:5)
    at async installEngine (/home/circleci/test262/node_modules/esvu/src/bin.js:121:3)
    at async main (/home/circleci/test262/node_modules/esvu/src/bin.js:168:7) {
  shortMessage: 'Command was killed with SIGABRT (Aborted): /home/circleci/.esvu/bin/chakra /tmp/esvu_chakra_test.js',
  command: '/home/circleci/.esvu/bin/chakra /tmp/esvu_chakra_test.js',
  exitCode: undefined,
  signal: 'SIGABRT',
  signalDescription: 'Aborted',
  stdout: '',
  stderr: 'The futex facility returned an unexpected error code.',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
esvu ✖ Some engines were not installed.
```
I can't reproduce this failure locally, ESVU's test passes fine.

Any suggestions?

**Comment by linusg** [comment]
Another datapoint - test262.fyi's ChakraCore test runs have been extremely flaky since the beginning of November and stabilized at a vastly lower score a couple of days ago. The last upstream commit is from March, unfortunately I have no idea what's happening either.

![image](https://github.com/tc39/test262/assets/19366641/657c5a40-92c5-47c5-8dea-97b43cafc1b8)
